apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dendrite-sqlite-storage
  namespace: dendrite
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dendrite-db-pvc
  namespace: dendrite
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
